import { StyleSheet } from "react-native";
import { COLORS, BUTTON_SIZES, SPACING, TYPOGRAPHY, BORDER_RADIUS, SHADOWS } from "@/theme/theme";

export const styles = StyleSheet.create({
  container: {
    padding: SPACING.xxl,
    paddingTop: SPACING.xxxl,
    gap: SPACING.lg,
    maxWidth: 1200,
    width: "100%",
    alignSelf: "center",
  },
  pageHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: SPACING.md,
  },
  pageTitle: { ...TYPOGRAPHY.h1 },
  pageSub: { ...TYPOGRAPHY.body, marginTop: 2 },
  headerControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    flexWrap: "wrap",
  },
  headerSep: { width: 1, height: 24, marginHorizontal: SPACING.xs },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: BORDER_RADIUS.full,
    borderWidth: 1,
  },
  chipText: { ...TYPOGRAPHY.label },
  chipTextActive: { color: "#fff", fontWeight: "600", fontSize: 13 },
  modeToggle: {
    flexDirection: "row",
    borderWidth: 1,
    borderRadius: BORDER_RADIUS.lg,
    overflow: "hidden",
  },
  modeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: BORDER_RADIUS.md,
  },
  modeBtnText: { ...TYPOGRAPHY.label },
  spinner: { marginTop: 40 },
  emptyState: { alignItems: "center", paddingVertical: 60, gap: SPACING.md },
  emptyText: { ...TYPOGRAPHY.body, fontStyle: "italic" },

  // Grid card
  gridCard: {
    borderRadius: BORDER_RADIUS.card,
    borderWidth: 1,
    overflow: "hidden",
    ...SHADOWS.sm,
  },
  gridDateBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
  },
  gridNavBtn: { ...BUTTON_SIZES.icon },
  gridDateLabel: { alignItems: "center", gap: 2 },
  gridDateText: { ...TYPOGRAPHY.bodyBold, fontSize: 16 },
  gridTodayHint: { ...TYPOGRAPHY.captionSmall, fontWeight: "600" },
  gridLegend: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.lg,
    paddingHorizontal: SPACING.lg,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  legendDot: { width: 12, height: 12, borderRadius: 3 },
  legendText: { ...TYPOGRAPHY.caption },
  gridHeaderText: { ...TYPOGRAPHY.labelSmall, letterSpacing: 0.5 },
  gridSectionLabel: { ...TYPOGRAPHY.labelSmall, letterSpacing: 0.8 },
  gridCellEmail: { fontSize: 9, fontWeight: "600", color: COLORS.error, textAlign: "center" },
  gridCellSeats: { fontSize: 9 },
  gridTableName: { ...TYPOGRAPHY.caption, fontWeight: "600" },
  gridTableSeats: { fontSize: 10 },

  // Table (list)
  tableCard: {
    borderRadius: BORDER_RADIUS.card,
    borderWidth: 1,
    ...SHADOWS.sm,
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
  },
  thCell: { ...TYPOGRAPHY.labelSmall, letterSpacing: 0.8 },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.lg,
    paddingVertical: 14,
  },
  colTime: { width: 140 },
  colGuest: { flex: 1, paddingHorizontal: SPACING.sm },
  colParty: { width: 64, alignItems: "flex-start" },
  colTable: { width: 64 },
  colStatus: { width: 108 },
  colAction: { width: 64, flexDirection: "row", alignItems: "center", gap: 6 },
  tdTime: { ...TYPOGRAPHY.bodyBold, fontSize: 14 },
  tdDate: { ...TYPOGRAPHY.caption, marginTop: 1 },
  tdGuest: { ...TYPOGRAPHY.body, fontWeight: "500" },
  tdNotes: { ...TYPOGRAPHY.caption, marginTop: 1 },
  partyPill: { flexDirection: "row", alignItems: "center", gap: 4 },
  tdParty: { ...TYPOGRAPHY.label },
  tdTableNum: { ...TYPOGRAPHY.body, fontSize: 14 },
  badge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: BORDER_RADIUS.full,
    alignSelf: "flex-start",
  },
  badgeText: { ...TYPOGRAPHY.labelSmall, fontWeight: "700" },
  rowActionBtn: { padding: 6, borderRadius: BORDER_RADIUS.md },

  // Card list (mobile)
  cardList: { gap: SPACING.md },
  listCard: {
    borderRadius: BORDER_RADIUS.xl,
    borderWidth: 1,
    padding: 14,
    ...SHADOWS.sm,
  },
  listCardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: SPACING.md,
  },
  listCardInfo: { flex: 1, gap: 4 },
  listCardRight: { alignItems: "flex-end" },

  newBookingBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    ...BUTTON_SIZES.small,
    borderRadius: BORDER_RADIUS.md,
  },
  newBookingBtnText: { ...TYPOGRAPHY.label, color: "#fff", fontWeight: "700" as const },
});
