import { StyleSheet } from "react-native";
import { theme } from "@/theme/theme";

export const styles = StyleSheet.create({
  container: {
    padding: theme.spacing.xxl,
    paddingTop: theme.spacing.xxxl,
    gap: theme.spacing.lg,
    maxWidth: 1200,
    width: "100%",
    alignSelf: "center",
  },
  pageHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: theme.spacing.md,
  },
  pageTitle: { ...theme.typography.h1 },
  pageSub: { ...theme.typography.body, marginTop: 2 },
  headerControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
    flexWrap: "wrap",
  },
  headerSep: { width: 1, height: 24, marginHorizontal: theme.spacing.xs },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: theme.borderRadius.full,
    borderWidth: 1,
  },
  chipText: { ...theme.typography.label },
  chipTextActive: { color: "#fff", fontWeight: "600", fontSize: 13 },
  modeToggle: {
    flexDirection: "row",
    borderWidth: 1,
    borderRadius: theme.borderRadius.lg,
    overflow: "hidden",
  },
  modeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.xs,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: theme.borderRadius.md,
  },
  modeBtnText: { ...theme.typography.label },
  spinner: { marginTop: 40 },
  emptyState: { alignItems: "center", paddingVertical: 60, gap: theme.spacing.md },
  emptyText: { ...theme.typography.body, fontStyle: "italic" },

  // Grid card
  gridCard: {
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    overflow: "hidden",
    ...theme.shadows.sm,
  },
  gridDateBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
    borderBottomWidth: 1,
  },
  gridNavBtn: { ...theme.buttonSizes.icon },
  gridDateLabel: { alignItems: "center", gap: 2 },
  gridDateText: { ...theme.typography.bodyBold, fontSize: 16 },
  gridTodayHint: { ...theme.typography.captionSmall, fontWeight: "600" },
  gridLegend: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.lg,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  legendDot: { width: 12, height: 12, borderRadius: 3 },
  legendText: { ...theme.typography.caption },
  gridHeaderText: { ...theme.typography.labelSmall, letterSpacing: 0.5 },
  gridSectionLabel: { ...theme.typography.labelSmall, letterSpacing: 0.8 },
  gridCellEmail: { fontSize: 9, fontWeight: "600", color: theme.colors.error, textAlign: "center" },
  gridCellSeats: { fontSize: 9 },
  gridTableName: { ...theme.typography.caption, fontWeight: "600" },
  gridTableSeats: { fontSize: 10 },

  // Table (list)
  tableCard: {
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    ...theme.shadows.sm,
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
  },
  thCell: { ...theme.typography.labelSmall, letterSpacing: 0.8 },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: 14,
  },
  colTime: { width: 140 },
  colGuest: { flex: 1, paddingHorizontal: theme.spacing.sm },
  colParty: { width: 64, alignItems: "flex-start" },
  colTable: { width: 64 },
  colStatus: { width: 108 },
  colAction: { width: 64, flexDirection: "row", alignItems: "center", gap: 6 },
  tdTime: { ...theme.typography.bodyBold, fontSize: 14 },
  tdDate: { ...theme.typography.caption, marginTop: 1 },
  tdGuest: { ...theme.typography.body, fontWeight: "500" },
  tdNotes: { ...theme.typography.caption, marginTop: 1 },
  partyPill: { flexDirection: "row", alignItems: "center", gap: 4 },
  tdParty: { ...theme.typography.label },
  tdTableNum: { ...theme.typography.body, fontSize: 14 },
  badge: {
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 3,
    borderRadius: theme.borderRadius.full,
    alignSelf: "flex-start",
  },
  badgeText: { ...theme.typography.labelSmall, fontWeight: "700" },
  rowActionBtn: { padding: 6, borderRadius: theme.borderRadius.md },

  // Card list (mobile)
  cardList: { gap: theme.spacing.md },
  listCard: {
    borderRadius: theme.borderRadius.xl,
    borderWidth: 1,
    padding: 14,
    ...theme.shadows.sm,
  },
  listCardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: theme.spacing.md,
  },
  listCardInfo: { flex: 1, gap: 4 },
  listCardRight: { alignItems: "flex-end" },

  newBookingBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.xs,
    ...theme.buttonSizes.small,
    borderRadius: theme.borderRadius.md,
  },
  newBookingBtnText: { ...theme.typography.label, color: "#fff", fontWeight: "700" as const },
});
