import { StyleSheet } from "react-native";
import {
  COLORS,
  BUTTON_SIZES,
  BADGE_COLORS,
  TYPOGRAPHY,
  SPACING,
  BORDER_RADIUS,
  SHADOWS,
} from "@/theme/theme";

export const styles = StyleSheet.create({
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  container: {
    padding: SPACING.xxl,
    paddingTop: SPACING.xxxl,
    gap: SPACING.md,
    maxWidth: 1100,
    width: "100%",
    alignSelf: "center",
  },
  pageHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  pageTitle: {
    ...TYPOGRAPHY.h1,
  },
  pageSub: {
    ...TYPOGRAPHY.body,
    marginTop: 2,
  },
  section: { gap: SPACING.lg },
  sectionHeading: {
    ...TYPOGRAPHY.labelSmall,
    letterSpacing: 0.8,
    marginBottom: 2,
    paddingHorizontal: 2,
  },
  // Base card style for all settings blocks
  secCard: {
    borderRadius: BORDER_RADIUS.card,
    borderWidth: 1,
    overflow: "hidden",
    ...SHADOWS.sm,
  },
  locationCard: {
    borderRadius: BORDER_RADIUS.card,
    borderWidth: 1,
    overflow: "hidden",
    ...SHADOWS.sm,
  },
  locationCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: SPACING.lg,
    gap: SPACING.md,
  },
  locationIcon: {
    width: 44,
    height: 44,
    borderRadius: BORDER_RADIUS.xl,
    alignItems: "center",
    justifyContent: "center",
  },
  locationMeta: { flex: 1, gap: 2 },
  locationName: { ...TYPOGRAPHY.bodyBold, fontSize: 16 },
  locationAddress: { ...TYPOGRAPHY.caption },
  activeBadge: {
    backgroundColor: BADGE_COLORS.active.bg,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: BORDER_RADIUS.full,
  },
  activeBadgeText: {
    ...TYPOGRAPHY.labelSmall,
    color: BADGE_COLORS.active.text,
    letterSpacing: 0.5,
  },
  locationStats: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderTopWidth: 1,
    gap: SPACING.lg,
  },
  locationStat: { alignItems: "center", gap: 1 },
  locationStatValue: { ...TYPOGRAPHY.h2, fontSize: 20 },
  locationStatLabel: { ...TYPOGRAPHY.captionSmall },
  locationStatDivider: { width: 1, height: 28 },
  locationCardAction: { flex: 1, alignItems: "flex-end" },
  configureBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
    ...BUTTON_SIZES.secondary,
    borderRadius: BORDER_RADIUS.md,
  },
  configureBtnText: { ...TYPOGRAPHY.label },
  expandedEditor: {
    borderTopWidth: 1,
    padding: SPACING.lg,
    gap: SPACING.xl, // Increased gap for better separation
  },
  editorSectionTitle: { ...TYPOGRAPHY.bodyBold, fontSize: 16 },
  editorSectionSub: { ...TYPOGRAPHY.label, marginTop: -10, opacity: 0.6 },
  // Inline editable rows
  editableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: SPACING.md,
    gap: SPACING.sm,
  },
  editableValue: { ...TYPOGRAPHY.bodyBold, flex: 1, fontSize: 16 },
  editableInput: { flex: 1 },
  rowActions: { flexDirection: "row", gap: SPACING.md, alignItems: "center" },
  smallBtn: {
    borderRadius: BORDER_RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
    ...BUTTON_SIZES.small,
  },
  smallBtnText: { ...TYPOGRAPHY.label, fontWeight: "600" },
  deleteText: { ...TYPOGRAPHY.label, color: COLORS.error },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
    ...BUTTON_SIZES.secondary, // Changed from primary for better hierarchy
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.primary,
  },
  addBtnText: { ...TYPOGRAPHY.bodyBold, color: "#fff", fontSize: 14 },
  addForm: { gap: SPACING.sm, paddingTop: SPACING.sm },
  addSaveBtn: { flex: 1 },
  cancelBtn: { ...BUTTON_SIZES.secondary, borderRadius: BORDER_RADIUS.md },
  cancelBtnText: { ...TYPOGRAPHY.label },
  actionBtn: {
    ...BUTTON_SIZES.secondary,
    borderRadius: BORDER_RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  actionBtnText: { ...TYPOGRAPHY.label },
  sectionBlock: {
    paddingBottom: SPACING.md,
  },
  tableList: {
    paddingLeft: SPACING.md,
    borderLeftWidth: 2,
    marginLeft: 4,
    gap: 2,
  },
  emptyNote: {
    ...TYPOGRAPHY.label,
    fontStyle: "italic",
    paddingVertical: SPACING.sm,
    opacity: 0.5,
  },
  tableItemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: SPACING.sm,
    gap: SPACING.sm,
  },
  tableInfo: { flex: 1, flexDirection: "row", alignItems: "center", gap: SPACING.sm },
  tableName: { ...TYPOGRAPHY.bodyBold, fontWeight: "500" },
  tableSeats: { ...TYPOGRAPHY.caption },
  tableEditFields: { flex: 1, flexDirection: "row", gap: SPACING.sm },
  flex1: { flex: 1 },
  flex2: { flex: 2 },
  infoForm: { gap: SPACING.md },
  field: { gap: SPACING.xs },
  fieldLabel: { ...TYPOGRAPHY.label },
  hoursRow: { flexDirection: "row", gap: SPACING.md, marginTop: SPACING.xs },
  hoursField: { flex: 1, gap: SPACING.xs },
  dayRow: { flexDirection: "row", gap: SPACING.xs, flexWrap: "wrap", marginTop: SPACING.xs },
  dayChip: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    minWidth: 56,
    minHeight: 40,
    borderRadius: BORDER_RADIUS.md,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  dayChipText: { ...TYPOGRAPHY.label },
  saveBtn: { marginTop: SPACING.sm },
  // Empty card
  emptyCard: {
    borderRadius: BORDER_RADIUS.card,
    borderWidth: 1,
    padding: 40,
    alignItems: "center",
    gap: SPACING.lg,
  },
  emptyText: { ...TYPOGRAPHY.body, fontStyle: "italic" },
  // Global settings rows
  globalRow: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: BORDER_RADIUS.xl,
    borderWidth: 1,
    padding: SPACING.lg,
    gap: SPACING.md,
    ...SHADOWS.sm,
  },
  globalRowIcon: {
    width: 38,
    height: 38,
    borderRadius: BORDER_RADIUS.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  globalRowText: { flex: 1, gap: 2 },
  globalRowTitle: { ...TYPOGRAPHY.bodyBold },
  globalRowSub: { ...TYPOGRAPHY.caption },
  comingSoonBadge: {
    backgroundColor: "rgba(10,126,164,0.1)",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 3,
    borderRadius: BORDER_RADIUS.full,
  },
  comingSoonText: { ...TYPOGRAPHY.captionSmall, fontWeight: "700", color: COLORS.primary },
  // Security card
  secHeader: { flexDirection: "row", alignItems: "center", gap: SPACING.md, padding: SPACING.lg },
  secIcon: {
    width: 40,
    height: 40,
    borderRadius: BORDER_RADIUS.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  secTitle: { ...TYPOGRAPHY.bodyBold },
  secSub: { ...TYPOGRAPHY.caption, marginTop: 1 },
  secRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.lg,
    borderTopWidth: 1,
    gap: SPACING.md,
  },
  secRowTitle: { ...TYPOGRAPHY.bodyBold },
  secRowSub: { ...TYPOGRAPHY.caption, marginTop: 1 },
  secBtn: { ...BUTTON_SIZES.secondary, borderWidth: 1, borderRadius: BORDER_RADIUS.md },
  secBtnText: { ...TYPOGRAPHY.label },
  secForm: {
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.lg,
    paddingTop: SPACING.md,
    borderTopWidth: 1,
    gap: SPACING.sm,
  },
  errorText: { ...TYPOGRAPHY.label, color: COLORS.error },
  successText: { ...TYPOGRAPHY.label, color: COLORS.success },
  successBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    padding: SPACING.md,
    paddingTop: 0,
  },
});
