import { StyleSheet } from "react-native";
import { theme } from "@/theme/theme";

export const styles = StyleSheet.create({
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  container: {
    padding: theme.spacing.xxl,
    paddingTop: theme.spacing.xxxl,
    gap: theme.spacing.lg,
    maxWidth: 1200,
    width: "100%",
    alignSelf: "center",
  },
  pageHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  pageTitle: {
    ...theme.typography.h1,
  },
  pageSub: {
    ...theme.typography.body,
    marginTop: 2,
  },
  section: { gap: theme.spacing.lg },
  sectionHeading: {
    ...theme.typography.labelSmall,
    letterSpacing: 0.8,
    marginBottom: 2,
    paddingHorizontal: 2,
  },
  // Base card style for all settings blocks
  secCard: {
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    overflow: "hidden",
    ...theme.shadows.sm,
  },
  locationCard: {
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    overflow: "hidden",
    ...theme.shadows.sm,
  },
  locationCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: theme.spacing.lg,
    gap: theme.spacing.md,
  },
  locationIcon: {
    width: 44,
    height: 44,
    borderRadius: theme.borderRadius.xl,
    alignItems: "center",
    justifyContent: "center",
  },
  locationMeta: { flex: 1, gap: 2 },
  locationName: { ...theme.typography.bodyBold, fontSize: 16 },
  locationAddress: { ...theme.typography.caption },
  activeBadge: {
    backgroundColor: theme.badge.active.bg,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    borderRadius: theme.borderRadius.full,
  },
  activeBadgeText: {
    ...theme.typography.labelSmall,
    color: theme.badge.active.text,
    letterSpacing: 0.5,
  },
  locationStats: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
    borderTopWidth: 1,
    gap: theme.spacing.lg,
  },
  locationStat: { alignItems: "center", gap: 1 },
  locationStatValue: { ...theme.typography.h2, fontSize: 20 },
  locationStatLabel: { ...theme.typography.captionSmall },
  locationStatDivider: { width: 1, height: 28 },
  locationCardAction: { flex: 1, alignItems: "flex-end" },
  configureBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.sm,
    ...theme.buttonSizes.secondary,
    borderRadius: theme.borderRadius.md,
  },
  configureBtnText: { ...theme.typography.label },
  expandedEditor: {
    borderTopWidth: 1,
    padding: theme.spacing.lg,
    gap: theme.spacing.xl, // Increased gap for better separation
  },
  editorSectionTitle: { ...theme.typography.bodyBold, fontSize: 16 },
  editorSectionSub: { ...theme.typography.label, marginTop: -10, opacity: 0.6 },
  // Inline editable rows
  editableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: theme.spacing.md,
    gap: theme.spacing.sm,
  },
  editableValue: { ...theme.typography.bodyBold, flex: 1, fontSize: 16 },
  editableInput: { flex: 1 },
  rowActions: { flexDirection: "row", gap: theme.spacing.md, alignItems: "center" },
  smallBtn: {
    borderRadius: theme.borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    ...theme.buttonSizes.small,
  },
  smallBtnText: { ...theme.typography.label, fontWeight: "600" },
  deleteText: { ...theme.typography.label, color: theme.colors.error },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.sm,
    ...theme.buttonSizes.secondary, // Changed from primary for better hierarchy
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.primary,
  },
  addBtnText: { ...theme.typography.bodyBold, color: "#fff", fontSize: 14 },
  addForm: { gap: theme.spacing.sm, paddingTop: theme.spacing.sm },
  addSaveBtn: { flex: 1 },
  cancelBtn: { ...theme.buttonSizes.secondary, borderRadius: theme.borderRadius.md },
  cancelBtnText: { ...theme.typography.label },
  actionBtn: {
    ...theme.buttonSizes.secondary,
    borderRadius: theme.borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
  },
  actionBtnText: { ...theme.typography.label },
  sectionBlock: {
    paddingBottom: theme.spacing.md,
  },
  tableList: {
    paddingLeft: theme.spacing.md,
    borderLeftWidth: 2,
    marginLeft: 4,
    gap: 2,
  },
  emptyNote: {
    ...theme.typography.label,
    fontStyle: "italic",
    paddingVertical: theme.spacing.sm,
    opacity: 0.5,
  },
  tableItemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: theme.spacing.sm,
    gap: theme.spacing.sm,
  },
  tableInfo: { flex: 1, flexDirection: "row", alignItems: "center", gap: theme.spacing.sm },
  tableName: { ...theme.typography.bodyBold, fontWeight: "500" },
  tableSeats: { ...theme.typography.caption },
  tableEditFields: { flex: 1, flexDirection: "row", gap: theme.spacing.sm },
  flex1: { flex: 1 },
  flex2: { flex: 2 },
  infoForm: { gap: theme.spacing.md },
  field: { gap: theme.spacing.xs },
  fieldLabel: { ...theme.typography.label },
  hoursRow: { flexDirection: "row", gap: theme.spacing.md, marginTop: theme.spacing.xs },
  hoursField: { flex: 1, gap: theme.spacing.xs },
  dayRow: {
    flexDirection: "row",
    gap: theme.spacing.xs,
    flexWrap: "wrap",
    marginTop: theme.spacing.xs,
  },
  dayChip: {
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
    minWidth: 56,
    minHeight: 40,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  dayChipText: { ...theme.typography.label },
  saveBtn: { marginTop: theme.spacing.sm },
  // Empty card
  emptyCard: {
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    padding: 40,
    alignItems: "center",
    gap: theme.spacing.lg,
  },
  emptyText: { ...theme.typography.body, fontStyle: "italic" },
  // Global settings rows
  globalRow: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: theme.borderRadius.xl,
    borderWidth: 1,
    padding: theme.spacing.lg,
    gap: theme.spacing.md,
    ...theme.shadows.sm,
  },
  globalRowIcon: {
    width: 38,
    height: 38,
    borderRadius: theme.borderRadius.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  globalRowText: { flex: 1, gap: 2 },
  globalRowTitle: { ...theme.typography.bodyBold },
  globalRowSub: { ...theme.typography.caption },
  comingSoonBadge: {
    backgroundColor: "rgba(10,126,164,0.1)",
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 3,
    borderRadius: theme.borderRadius.full,
  },
  comingSoonText: {
    ...theme.typography.captionSmall,
    fontWeight: "700",
    color: theme.colors.primary,
  },
  // Security card
  secHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
  },
  secIcon: {
    width: 40,
    height: 40,
    borderRadius: theme.borderRadius.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  secTitle: { ...theme.typography.bodyBold },
  secSub: { ...theme.typography.caption, marginTop: 1 },
  secRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.lg,
    borderTopWidth: 1,
    gap: theme.spacing.md,
  },
  secRowTitle: { ...theme.typography.bodyBold },
  secRowSub: { ...theme.typography.caption, marginTop: 1 },
  secBtn: { ...theme.buttonSizes.secondary, borderWidth: 1, borderRadius: theme.borderRadius.md },
  secBtnText: { ...theme.typography.label },
  secForm: {
    paddingHorizontal: theme.spacing.lg,
    paddingBottom: theme.spacing.lg,
    paddingTop: theme.spacing.md,
    borderTopWidth: 1,
    gap: theme.spacing.sm,
  },
  errorText: { ...theme.typography.label, color: theme.colors.error },
  successText: { ...theme.typography.label, color: theme.colors.success },
  successBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
    padding: theme.spacing.md,
    paddingTop: 0,
  },
});
